version: '3'

services:
  frontend:
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: gf-frontend
    container_name: gf-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
  
  backend:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gf-backend
    container_name: gf-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
    env_file:
      - .env
  
  database:
    tty: true
    build:
      context: ./database
      dockerfile: Dockerfile
    image: gf-database
    container_name: gf-database
    ports:
      - "5432:5432"
    volumes:
      - ./database/db:/var/lib/postgresql/data
    env_file:
      - .env